Nest BaskEnd Project/Nest BaskEnd Project/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nest_BaskEnd_Project.DAL;
using Nest_BaskEnd_Project.Models;
using Nest_BaskEnd_Project.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nest_BaskEnd_Project.Controllers
{
    public class ProductController : Controller
    {
        private AppDbContext _context { get; }
        public ProductController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? page)
        {           
            //ViewBag.ProductCount = _context.Products.Where(p => p.IsDeleted == false).Count();
            ViewBag.Page = page;
            ViewBag.Categories = _context.Categories.Where(p => p.IsDeleted == false).Include(c => c.Products);

            return View();
        }
        public IActionResult LoadMore(int skip)
        {
            IQueryable<Product> p = _context.Products.Where(p => p.IsDeleted == false);
            int productCount = p.Count();
            if (productCount <= skip)
            {
                return Json(new
                {
                    message = "You aren't smart"
                });
            }
            return PartialView("_ProductPartial", p
                                    .OrderByDescending(p => p.Id)
                                    .Skip(skip)
                                    .Take(10)
                                    .Include(p => p.ProductImages)
                                    .Include(p => p.Category));
            
        }
        public IActionResult CategoryFilter(int CategoryId)
        {
            if (_context.Categories.Find(CategoryId) == null) return NotFound();
            return PartialView("_ProductPartial", _context.Products.Where(p => p.IsDeleted == false && p.CategoryId == CategoryId)
                                .OrderByDescending(p => p.Id)
                                .Include(p => p.ProductImages)
                                .Include(p => p.Category));
        }
        public IActionResult Cart()
        {
            List<BasketVM> basket = GetBasket();
            List<BasketItemsVM> basketItems = new List<BasketItemsVM>();
            foreach (var item in basket)
            {
                Product dbproduct = _context.Products.Include(p=>p.ProductImages).FirstOrDefault(p=>p.Id==item.ProductId);
                if (dbproduct == null) continue;
                BasketItemsVM basketItem = new BasketItemsVM { 
                    ProductId= dbproduct.Id,
                    Image=dbproduct.ProductImages.FirstOrDefault(p=>p.IsFront==true).Image,
                    Name = dbproduct.Name,
                    Price= dbproduct.SellPrice,
                    Raiting=dbproduct.Raiting,
                    IsActive=dbproduct.StockCount>0?true:false,
                    Count=item.Count
                };
                basketItems.Add(basketItem);
            }
            return View(basketItems);
        }

        public IActionResult Delete(int id)
        {
            List<BasketVM> basketdelete = GetBasket();
            BasketVM b= basketdelete.Find(b=>b.ProductId==id);
            basketdelete.Remove(b);
            Response.Cookies.Append("Basket", JsonConvert.SerializeObject(basketdelete));
            return RedirectToAction(nameof(Cart));
        }
        public IActionResult Basket()
        {
            List<BasketVM> product = JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies["Basket"]);
            return Json(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id == null) return BadRequest();
            Product dbProduct = await _context.Products.FindAsync(id);
            if (dbProduct == null) return NotFound();
            UpdateBasketItems((int)id);
            return RedirectToAction(nameof(Index));
        }
        private List<BasketVM> GetBasket()
        {
            List<BasketVM> basketItems = new List<BasketVM>();
            if (Request.Cookies["Basket"] != null)
            {
                basketItems = JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies["Basket"]);
            }
            return basketItems;
        }
        private void UpdateBasketItems(int id)
        {
            List<BasketVM> basketItems = GetBasket();
            BasketVM existItem = basketItems.Find(bs => bs.ProductId == id);
            if (existItem != null) existItem.Count++;
            else
            {
                existItem = new BasketVM
                {
                    ProductId = id,
                    Count = 1
                };
               basketItems.Add(existItem);
            }
            Response.Cookies.Append("Basket", JsonConvert.SerializeObject(basketItems));
        }

    }
}

Nest BaskEnd Project/Nest BaskEnd Project/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nest_BaskEnd_Project.DAL;
using Nest_BaskEnd_Project.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nest_BaskEnd_Project.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private AppDbContext _context { get;  }
        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            SettingsVM vM = new SettingsVM();
            vM.KeyValuePairs = await _context.Settings.ToDictionaryAsync(p => p.Key, p => p.Value);
            return View(await Task.FromResult(vM));
        }

    }
}

Nest BaskEnd Project/Nest BaskEnd Project/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nest_BaskEnd_Project.DAL;
using Nest_BaskEnd_Project.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nest_BaskEnd_Project.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private AppDbContext _context { get; }
        private IHttpContextAccessor _accessor { get; }

        public HeaderViewComponent(AppDbContext context, IHttpContextAccessor accessor)
        {
            _context = context;
            _accessor = accessor;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            SettingsVM vM = new SettingsVM();
            vM.KeyValuePairs = await  _context.Settings.ToDictionaryAsync(p => p.Key, p => p.Value);
            if(_accessor.HttpContext.Request.Cookies["Basket"] != null)
            {
            List<BasketVM> basket =  JsonConvert.DeserializeObject<List<BasketVM>>(_accessor.HttpContext.Request.Cookies["Basket"]);
            
            vM.Count = basket.Sum(b => b.Count);
            }
            return View(vM);
        }

    }
}

Nest BaskEnd Project/Nest BaskEnd Project/Views/Shared/_Layout.cshtml
@*@using Nest_BaskEnd_Project.Services
@inject LayoutServices service
@{ 
    Dictionary<string, string> settings = service.GetSettings();
    int BasketItemCount = service.BasketItemCount();
}*@
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <title>Nest - Multipurpose eCommerce HTML Template</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta property="og:title" content="" />
    <meta property="og:type" content="" />
    <meta property="og:url" content="" />
    <meta property="og:image" content="" />
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/imgs/theme/favicon.svg" />

    <!-- Template CSS -->
    <link rel="stylesheet" href="~/assets/css/plugins/animate.min.css" />
    <link rel="stylesheet" href="~/assets/css/main.css?v=4.0" />
    @RenderSection("styles", false)
</head>

<body>

      @await Component.InvokeAsync("Header")
    
    <!--End header-->
    <main class="main">
        @RenderBody()
    </main>
     @await Component.InvokeAsync("Footer")
    

    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="text-center">
                    <img src="~/assets/imgs/theme/loading.gif" alt="" />
                </div>
            </div>
        </div>
    </div>
    <!-- Vendor JS-->
    @RenderSection("scripts", false)
    <script src="~/assets/js/vendor/modernizr-3.6.0.min.js"></script>
    <script src="~/assets/js/vendor/jquery-3.6.0.min.js"></script>
    <script src="~/assets/js/vendor/jquery-migrate-3.3.0.min.js"></script>
    <script src="~/assets/js/vendor/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/plugins/slick.js"></script>
    <script src="~/assets/js/plugins/jquery.syotimer.min.js"></script>
    <script src="~/assets/js/plugins/waypoints.js"></script>
    <script src="~/assets/js/plugins/wow.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.js"></script>
    <script src="~/assets/js/plugins/magnific-popup.js"></script>
    <script src="~/assets/js/plugins/select2.min.js"></script>
    <script src="~/assets/js/plugins/counterup.js"></script>
    <script src="~/assets/js/plugins/jquery.countdown.min.js"></script>
    <script src="~/assets/js/plugins/images-loaded.js"></script>
    <script src="~/assets/js/plugins/isotope.js"></script>
    <script src="~/assets/js/plugins/scrollup.js"></script>
    <script src="~/assets/js/plugins/jquery.vticker-min.js"></script>
    <script src="~/assets/js/plugins/jquery.theia.sticky.js"></script>
    <script src="~/assets/js/plugins/jquery.elevatezoom.js"></script>
    <!-- Template  JS -->
    <script src="~/assets/js/main.js?v=4.0"></script>
    <script src="~/assets/js/shop.js?v=4.0"></script>
</body>
</html>

Nest BaskEnd Project/Nest BaskEnd Project/Views/Shared/_ProductPartial.cshtml
@model IEnumerable<Product>
@foreach (var item in Model)
{
    <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
        <div class="product-cart-wrap mb-30">
            <div class="product-img-action-wrap">
                <div class="product-img product-img-zoom">
                    <a href="shop-product-right.html">
                        <img class="default-img" width="240" height="240" src="~/assets/imgs/shop/@item.ProductImages.FirstOrDefault(pi=>pi.IsFront==true).Image" alt="" />
                        <img class="hover-img" width="240" height="240" src="~/assets/imgs/shop/@item.ProductImages.FirstOrDefault(pi=>pi.IsBack==true).Image" alt="" />
                    </a>
                </div>
                <div class="product-action-1">
                    <a aria-label="Add To Wishlist" class="action-btn" href="shop-wishlist.html"><i class="fi-rs-heart"></i></a>
                    <a aria-label="Quick view" class="action-btn" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-eye"></i></a>
                </div>
                <div class="product-badges product-badges-position product-badges-mrg">
                    @if (item.StockCount == 0)
                    {
                        <span class="hot">Bitdi</span>
                    }
                </div>
            </div>
            <div class="product-content-wrap">
                <div class="product-category">
                    <a href="shop-grid-right.html">@item.Category.Name</a>
                </div>
                <h2><a asp-action="Details" asp-route-id="@item.Id">@item.Name</a></h2>
                <div class="product-rate-cover">
                    <div class="product-rate d-inline-block">
                        <div class="product-rating" style="width: @(item.Raiting*20)%"></div>
                    </div>
                    <span class="font-small ml-5 text-muted"> (@item.Raiting)</span>
                </div>
                @*<div>
                        <span class="font-small text-muted">By <a href="vendor-details-1.html">Stouffer</a></span>
                    </div>*@
                <div class="product-card-bottom">
                    <div class="product-price">
                        <span>$@item.SellPrice</span>
                        @*<span class="old-price">$55.8</span>*@
                    </div>
                    <form method="post" asp-controller="Product" asp-action="AddBasket" asp-route-id="@item.Id" class="add-cart">
                        <button type="submit" class="add" ><i class="fi-rs-shopping-cart mr-5"></i>Add </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}